#if os(macOS)
// Generated by Scripts/diffs/generate-native-symbols.py from @pierre/diffs src/sprite.ts.
// Upstream vector artwork is Apache-2.0 licensed; see LICENSE.
// Arc conversion is performed at generation time, never while rendering.
import AppKit

@MainActor enum DiffSymbol: CaseIterable {
    case plus, fileCode, modified, added, deleted, moved, expand, expandAll

    func draw(in rect: NSRect, color: NSColor, flipY: Bool = false) {
        NSGraphicsContext.saveGraphicsState()
        defer { NSGraphicsContext.restoreGraphicsState() }
        let transform = NSAffineTransform()
        transform.translateX(by: rect.minX, yBy: flipY ? rect.maxY : rect.minY)
        transform.scaleX(by: rect.width / 16, yBy: (flipY ? -1 : 1) * rect.height / 16)
        transform.concat(); color.setFill()
        for path in Self.paths[self] ?? [] { path.fill() }
    }

    private static let paths: [DiffSymbol: [NSBezierPath]] = {
        var result: [DiffSymbol: [NSBezierPath]] = [:]
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 8.0000000, y: 3.0000000))
                path.curve(to: .init(x: 8.7500000, y: 3.7500000), controlPoint1: .init(x: 8.4142136, y: 3.0000000), controlPoint2: .init(x: 8.7500000, y: 3.3357864))
                path.line(to: .init(x: 8.7500000, y: 7.2500000))
                path.line(to: .init(x: 12.2500000, y: 7.2500000))
                path.curve(to: .init(x: 13.0000000, y: 8.0000000), controlPoint1: .init(x: 12.6642136, y: 7.2500000), controlPoint2: .init(x: 13.0000000, y: 7.5857864))
                path.curve(to: .init(x: 12.2500000, y: 8.7500000), controlPoint1: .init(x: 13.0000000, y: 8.4142136), controlPoint2: .init(x: 12.6642136, y: 8.7500000))
                path.line(to: .init(x: 8.7500000, y: 8.7500000))
                path.line(to: .init(x: 8.7500000, y: 12.2500000))
                path.curve(to: .init(x: 8.0000000, y: 13.0000000), controlPoint1: .init(x: 8.7500000, y: 12.6642136), controlPoint2: .init(x: 8.4142136, y: 13.0000000))
                path.curve(to: .init(x: 7.2500000, y: 12.2500000), controlPoint1: .init(x: 7.5857864, y: 13.0000000), controlPoint2: .init(x: 7.2500000, y: 12.6642136))
                path.line(to: .init(x: 7.2500000, y: 8.7500000))
                path.line(to: .init(x: 3.7500000, y: 8.7500000))
                path.curve(to: .init(x: 3.0000000, y: 8.0000000), controlPoint1: .init(x: 3.3357864, y: 8.7500000), controlPoint2: .init(x: 3.0000000, y: 8.4142136))
                path.curve(to: .init(x: 3.7500000, y: 7.2500000), controlPoint1: .init(x: 3.0000000, y: 7.5857864), controlPoint2: .init(x: 3.3357864, y: 7.2500000))
                path.line(to: .init(x: 7.2500000, y: 7.2500000))
                path.line(to: .init(x: 7.2500000, y: 3.7500000))
                path.curve(to: .init(x: 8.0000000, y: 3.0000000), controlPoint1: .init(x: 7.2500000, y: 3.3357864), controlPoint2: .init(x: 7.5857864, y: 3.0000000))
                layers.append(path)
            }
            result[.plus] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 10.7500000, y: 0.0000000))
                path.curve(to: .init(x: 11.2800000, y: 0.2200000), controlPoint1: .init(x: 10.9490000, y: 0.0000000), controlPoint2: .init(x: 11.1400000, y: 0.0800000))
                path.line(to: .init(x: 14.7800000, y: 3.7200000))
                path.curve(to: .init(x: 15.0000000, y: 4.2500000), controlPoint1: .init(x: 14.9200000, y: 3.8600000), controlPoint2: .init(x: 15.0000000, y: 4.0510000))
                path.line(to: .init(x: 15.0000000, y: 13.2500000))
                path.curve(to: .init(x: 12.2500000, y: 16.0000000), controlPoint1: .init(x: 15.0000000, y: 14.7687831), controlPoint2: .init(x: 13.7687831, y: 16.0000000))
                path.line(to: .init(x: 3.7500000, y: 16.0000000))
                path.curve(to: .init(x: 1.0000000, y: 13.2500000), controlPoint1: .init(x: 2.2312169, y: 16.0000000), controlPoint2: .init(x: 1.0000000, y: 14.7687831))
                path.line(to: .init(x: 1.0000000, y: 2.7500000))
                path.curve(to: .init(x: 3.7500000, y: 0.0000000), controlPoint1: .init(x: 1.0000000, y: 1.2312169), controlPoint2: .init(x: 2.2312169, y: 0.0000000))
                path.close()
                path.move(to: .init(x: 3.7500000, y: 1.5000000))
                path.curve(to: .init(x: 2.5000000, y: 2.7500000), controlPoint1: .init(x: 3.0600000, y: 1.5000000), controlPoint2: .init(x: 2.5000000, y: 2.0600000))
                path.line(to: .init(x: 2.5000000, y: 13.2500000))
                path.curve(to: .init(x: 3.7500000, y: 14.5000000), controlPoint1: .init(x: 2.5000000, y: 13.9400000), controlPoint2: .init(x: 3.0600000, y: 14.5000000))
                path.line(to: .init(x: 12.2500000, y: 14.5000000))
                path.curve(to: .init(x: 13.5000000, y: 13.2500000), controlPoint1: .init(x: 12.9400000, y: 14.5000000), controlPoint2: .init(x: 13.5000000, y: 13.9400000))
                path.line(to: .init(x: 13.5000000, y: 5.0000000))
                path.line(to: .init(x: 12.2500000, y: 5.0000000))
                path.curve(to: .init(x: 10.0000000, y: 2.7500000), controlPoint1: .init(x: 11.0073593, y: 5.0000000), controlPoint2: .init(x: 10.0000000, y: 3.9926407))
                path.line(to: .init(x: 10.0000000, y: 1.5000000))
                path.close()
                layers.append(path)
            }
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 7.2480000, y: 6.1900000))
                path.curve(to: .init(x: 7.3110000, y: 7.2480000), controlPoint1: .init(x: 7.5572571, y: 6.4649066), controlPoint2: .init(x: 7.5854480, y: 6.9383359))
                path.line(to: .init(x: 5.7530000, y: 9.0000000))
                path.line(to: .init(x: 7.3110000, y: 10.7520000))
                path.curve(to: .init(x: 7.2480000, y: 11.8110000), controlPoint1: .init(x: 7.5860378, y: 11.0618317), controlPoint2: .init(x: 7.5578317, y: 11.5359622))
                path.curve(to: .init(x: 6.1890000, y: 11.7480000), controlPoint1: .init(x: 6.9381683, y: 12.0860378), controlPoint2: .init(x: 6.4640378, y: 12.0578317))
                path.line(to: .init(x: 4.1890000, y: 9.4980000))
                path.curve(to: .init(x: 4.1890000, y: 8.5020000), controlPoint1: .init(x: 3.9367326, y: 9.2139208), controlPoint2: .init(x: 3.9367326, y: 8.7860792))
                path.line(to: .init(x: 6.1890000, y: 6.2520000))
                path.curve(to: .init(x: 6.7059312, y: 6.0006122), controlPoint1: .init(x: 6.3210866, y: 6.1028779), controlPoint2: .init(x: 6.5070730, y: 6.0124312))
                path.curve(to: .init(x: 7.2490000, y: 6.1890000), controlPoint1: .init(x: 6.9047894, y: 5.9887933), controlPoint2: .init(x: 7.1001799, y: 6.0565733))
                path.move(to: .init(x: 8.6900000, y: 7.2480000))
                path.curve(to: .init(x: 8.5151811, y: 6.5009630), controlPoint1: .init(x: 8.4991336, y: 7.0498930), controlPoint2: .init(x: 8.4320409, y: 6.7631920))
                path.curve(to: .init(x: 9.0884952, y: 5.9911229), controlPoint1: .init(x: 8.5983213, y: 6.2387339), controlPoint2: .init(x: 8.8183502, y: 6.0430654))
                path.curve(to: .init(x: 9.8100000, y: 6.2520000), controlPoint1: .init(x: 9.3586402, y: 5.9391804), controlPoint2: .init(x: 9.6355424, y: 6.0393009))
                path.line(to: .init(x: 11.8100000, y: 8.5020000))
                path.curve(to: .init(x: 11.8100000, y: 9.4980000), controlPoint1: .init(x: 12.0622674, y: 8.7860792), controlPoint2: .init(x: 12.0622674, y: 9.2139208))
                path.line(to: .init(x: 9.8100000, y: 11.7480000))
                path.curve(to: .init(x: 9.0884952, y: 12.0088771), controlPoint1: .init(x: 9.6355424, y: 11.9606991), controlPoint2: .init(x: 9.3586402, y: 12.0608196))
                path.curve(to: .init(x: 8.5151811, y: 11.4990370), controlPoint1: .init(x: 8.8183502, y: 11.9569346), controlPoint2: .init(x: 8.5983213, y: 11.7612661))
                path.curve(to: .init(x: 8.6900000, y: 10.7520000), controlPoint1: .init(x: 8.4320409, y: 11.2368080), controlPoint2: .init(x: 8.4991336, y: 10.9501070))
                path.line(to: .init(x: 10.2450000, y: 9.0000000))
                path.close()
                layers.append(path)
            }
            result[.fileCode] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 1.5000000, y: 8.0000000))
                path.curve(to: .init(x: 1.7880000, y: 11.7040000), controlPoint1: .init(x: 1.5000000, y: 9.6130000), controlPoint2: .init(x: 1.5880000, y: 10.8060000))
                path.curve(to: .init(x: 2.5900000, y: 13.4100000), controlPoint1: .init(x: 1.9840000, y: 12.5840000), controlPoint2: .init(x: 2.2660000, y: 13.0850000))
                path.curve(to: .init(x: 4.2960000, y: 14.2120000), controlPoint1: .init(x: 2.9140000, y: 13.7350000), controlPoint2: .init(x: 3.4160000, y: 14.0170000))
                path.curve(to: .init(x: 8.0000000, y: 14.5000000), controlPoint1: .init(x: 5.1940000, y: 14.4120000), controlPoint2: .init(x: 6.3870000, y: 14.5000000))
                path.curve(to: .init(x: 11.7040000, y: 14.2120000), controlPoint1: .init(x: 9.6130000, y: 14.5000000), controlPoint2: .init(x: 10.8060000, y: 14.4120000))
                path.curve(to: .init(x: 13.4100000, y: 13.4100000), controlPoint1: .init(x: 12.5840000, y: 14.0170000), controlPoint2: .init(x: 13.0850000, y: 13.7340000))
                path.curve(to: .init(x: 14.2120000, y: 11.7040000), controlPoint1: .init(x: 13.7350000, y: 13.0860000), controlPoint2: .init(x: 14.0170000, y: 12.5840000))
                path.curve(to: .init(x: 14.5000000, y: 8.0000000), controlPoint1: .init(x: 14.4120000, y: 10.8060000), controlPoint2: .init(x: 14.5000000, y: 9.6130000))
                path.curve(to: .init(x: 14.2120000, y: 4.2960000), controlPoint1: .init(x: 14.5000000, y: 6.3870000), controlPoint2: .init(x: 14.4120000, y: 5.1940000))
                path.curve(to: .init(x: 13.4100000, y: 2.5900000), controlPoint1: .init(x: 14.0170000, y: 3.4160000), controlPoint2: .init(x: 13.7340000, y: 2.9150000))
                path.curve(to: .init(x: 11.7040000, y: 1.7880000), controlPoint1: .init(x: 13.0860000, y: 2.2650000), controlPoint2: .init(x: 12.5840000, y: 1.9840000))
                path.curve(to: .init(x: 8.0000000, y: 1.5000000), controlPoint1: .init(x: 10.8060000, y: 1.5880000), controlPoint2: .init(x: 9.6130000, y: 1.5000000))
                path.curve(to: .init(x: 4.2960000, y: 1.7880000), controlPoint1: .init(x: 6.3870000, y: 1.5000000), controlPoint2: .init(x: 5.1940000, y: 1.5880000))
                path.curve(to: .init(x: 2.5900000, y: 2.5900000), controlPoint1: .init(x: 3.4160000, y: 1.9840000), controlPoint2: .init(x: 2.9150000, y: 2.2660000))
                path.curve(to: .init(x: 1.7880000, y: 4.2960000), controlPoint1: .init(x: 2.2650000, y: 2.9140000), controlPoint2: .init(x: 1.9840000, y: 3.4160000))
                path.curve(to: .init(x: 1.5000000, y: 8.0000000), controlPoint1: .init(x: 1.5880000, y: 5.1940000), controlPoint2: .init(x: 1.5000000, y: 6.3870000))
                path.move(to: .init(x: 0.0000000, y: 8.0000000))
                path.curve(to: .init(x: 8.0000000, y: 0.0000000), controlPoint1: .init(x: 0.0000000, y: 1.4120000), controlPoint2: .init(x: 1.4120000, y: 0.0000000))
                path.curve(to: .init(x: 16.0000000, y: 8.0000000), controlPoint1: .init(x: 14.5880000, y: 0.0000000), controlPoint2: .init(x: 16.0000000, y: 1.4120000))
                path.curve(to: .init(x: 8.0000000, y: 16.0000000), controlPoint1: .init(x: 16.0000000, y: 14.5880000), controlPoint2: .init(x: 14.5880000, y: 16.0000000))
                path.curve(to: .init(x: 0.0000000, y: 8.0000000), controlPoint1: .init(x: 1.4120000, y: 16.0000000), controlPoint2: .init(x: 0.0000000, y: 14.5880000))
                path.move(to: .init(x: 8.0000000, y: 11.0000000))
                path.curve(to: .init(x: 11.0000000, y: 8.0000000), controlPoint1: .init(x: 9.6568542, y: 11.0000000), controlPoint2: .init(x: 11.0000000, y: 9.6568542))
                path.curve(to: .init(x: 8.0000000, y: 5.0000000), controlPoint1: .init(x: 11.0000000, y: 6.3431458), controlPoint2: .init(x: 9.6568542, y: 5.0000000))
                path.curve(to: .init(x: 5.0000000, y: 8.0000000), controlPoint1: .init(x: 6.3431458, y: 5.0000000), controlPoint2: .init(x: 5.0000000, y: 6.3431458))
                path.curve(to: .init(x: 8.0000000, y: 11.0000000), controlPoint1: .init(x: 5.0000000, y: 9.6568542), controlPoint2: .init(x: 6.3431458, y: 11.0000000))
                layers.append(path)
            }
            result[.modified] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 8.0000000, y: 4.0000000))
                path.curve(to: .init(x: 8.7500000, y: 4.7500000), controlPoint1: .init(x: 8.4142136, y: 4.0000000), controlPoint2: .init(x: 8.7500000, y: 4.3357864))
                path.line(to: .init(x: 8.7500000, y: 7.2500000))
                path.line(to: .init(x: 11.2500000, y: 7.2500000))
                path.curve(to: .init(x: 12.0000000, y: 8.0000000), controlPoint1: .init(x: 11.6642136, y: 7.2500000), controlPoint2: .init(x: 12.0000000, y: 7.5857864))
                path.curve(to: .init(x: 11.2500000, y: 8.7500000), controlPoint1: .init(x: 12.0000000, y: 8.4142136), controlPoint2: .init(x: 11.6642136, y: 8.7500000))
                path.line(to: .init(x: 8.7500000, y: 8.7500000))
                path.line(to: .init(x: 8.7500000, y: 11.2500000))
                path.curve(to: .init(x: 8.0000000, y: 12.0000000), controlPoint1: .init(x: 8.7500000, y: 11.6642136), controlPoint2: .init(x: 8.4142136, y: 12.0000000))
                path.curve(to: .init(x: 7.2500000, y: 11.2500000), controlPoint1: .init(x: 7.5857864, y: 12.0000000), controlPoint2: .init(x: 7.2500000, y: 11.6642136))
                path.line(to: .init(x: 7.2500000, y: 8.7500000))
                path.line(to: .init(x: 4.7500000, y: 8.7500000))
                path.curve(to: .init(x: 4.0000000, y: 8.0000000), controlPoint1: .init(x: 4.3357864, y: 8.7500000), controlPoint2: .init(x: 4.0000000, y: 8.4142136))
                path.curve(to: .init(x: 4.7500000, y: 7.2500000), controlPoint1: .init(x: 4.0000000, y: 7.5857864), controlPoint2: .init(x: 4.3357864, y: 7.2500000))
                path.line(to: .init(x: 7.2500000, y: 7.2500000))
                path.line(to: .init(x: 7.2500000, y: 4.7500000))
                path.curve(to: .init(x: 8.0000000, y: 4.0000000), controlPoint1: .init(x: 7.2500000, y: 4.3357864), controlPoint2: .init(x: 7.5857864, y: 4.0000000))
                layers.append(path)
            }
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 1.7880000, y: 4.2960000))
                path.curve(to: .init(x: 2.5900000, y: 2.5900000), controlPoint1: .init(x: 1.9840000, y: 3.4160000), controlPoint2: .init(x: 2.2660000, y: 2.9150000))
                path.curve(to: .init(x: 4.2960000, y: 1.7880000), controlPoint1: .init(x: 2.9140000, y: 2.2650000), controlPoint2: .init(x: 3.4160000, y: 1.9840000))
                path.curve(to: .init(x: 8.0000000, y: 1.5000000), controlPoint1: .init(x: 5.1940000, y: 1.5880000), controlPoint2: .init(x: 6.3870000, y: 1.5000000))
                path.curve(to: .init(x: 11.7040000, y: 1.7880000), controlPoint1: .init(x: 9.6130000, y: 1.5000000), controlPoint2: .init(x: 10.8060000, y: 1.5880000))
                path.curve(to: .init(x: 13.4100000, y: 2.5900000), controlPoint1: .init(x: 12.5840000, y: 1.9840000), controlPoint2: .init(x: 13.0850000, y: 2.2660000))
                path.curve(to: .init(x: 14.2120000, y: 4.2960000), controlPoint1: .init(x: 13.7350000, y: 2.9140000), controlPoint2: .init(x: 14.0170000, y: 3.4160000))
                path.curve(to: .init(x: 14.5000000, y: 8.0000000), controlPoint1: .init(x: 14.4120000, y: 5.1940000), controlPoint2: .init(x: 14.5000000, y: 6.3870000))
                path.curve(to: .init(x: 14.2120000, y: 11.7040000), controlPoint1: .init(x: 14.5000000, y: 9.6130000), controlPoint2: .init(x: 14.4120000, y: 10.8060000))
                path.curve(to: .init(x: 13.4100000, y: 13.4100000), controlPoint1: .init(x: 14.0170000, y: 12.5840000), controlPoint2: .init(x: 13.7340000, y: 13.0850000))
                path.curve(to: .init(x: 11.7040000, y: 14.2120000), controlPoint1: .init(x: 13.0860000, y: 13.7350000), controlPoint2: .init(x: 12.5840000, y: 14.0170000))
                path.curve(to: .init(x: 8.0000000, y: 14.5000000), controlPoint1: .init(x: 10.8060000, y: 14.4120000), controlPoint2: .init(x: 9.6130000, y: 14.5000000))
                path.curve(to: .init(x: 4.2960000, y: 14.2120000), controlPoint1: .init(x: 6.3870000, y: 14.5000000), controlPoint2: .init(x: 5.1940000, y: 14.4120000))
                path.curve(to: .init(x: 2.5900000, y: 13.4100000), controlPoint1: .init(x: 3.4160000, y: 14.0170000), controlPoint2: .init(x: 2.9150000, y: 13.7340000))
                path.curve(to: .init(x: 1.7880000, y: 11.7040000), controlPoint1: .init(x: 2.2650000, y: 13.0860000), controlPoint2: .init(x: 1.9840000, y: 12.5840000))
                path.curve(to: .init(x: 1.5000000, y: 8.0000000), controlPoint1: .init(x: 1.5880000, y: 10.8060000), controlPoint2: .init(x: 1.5000000, y: 9.6130000))
                path.curve(to: .init(x: 1.7880000, y: 4.2960000), controlPoint1: .init(x: 1.5000000, y: 6.3870000), controlPoint2: .init(x: 1.5880000, y: 5.1940000))
                path.move(to: .init(x: 8.0000000, y: 0.0000000))
                path.curve(to: .init(x: 0.0000000, y: 8.0000000), controlPoint1: .init(x: 1.4120000, y: 0.0000000), controlPoint2: .init(x: 0.0000000, y: 1.4120000))
                path.curve(to: .init(x: 8.0000000, y: 16.0000000), controlPoint1: .init(x: 0.0000000, y: 14.5880000), controlPoint2: .init(x: 1.4120000, y: 16.0000000))
                path.curve(to: .init(x: 16.0000000, y: 8.0000000), controlPoint1: .init(x: 14.5880000, y: 16.0000000), controlPoint2: .init(x: 16.0000000, y: 14.5880000))
                path.curve(to: .init(x: 8.0000000, y: 0.0000000), controlPoint1: .init(x: 16.0000000, y: 1.4120000), controlPoint2: .init(x: 14.5880000, y: 0.0000000))
                layers.append(path)
            }
            result[.added] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 4.0000000, y: 8.0000000))
                path.curve(to: .init(x: 4.7500000, y: 7.2500000), controlPoint1: .init(x: 4.0000000, y: 7.5857864), controlPoint2: .init(x: 4.3357864, y: 7.2500000))
                path.line(to: .init(x: 11.2500000, y: 7.2500000))
                path.curve(to: .init(x: 12.0000000, y: 8.0000000), controlPoint1: .init(x: 11.6642136, y: 7.2500000), controlPoint2: .init(x: 12.0000000, y: 7.5857864))
                path.curve(to: .init(x: 11.2500000, y: 8.7500000), controlPoint1: .init(x: 12.0000000, y: 8.4142136), controlPoint2: .init(x: 11.6642136, y: 8.7500000))
                path.line(to: .init(x: 4.7500000, y: 8.7500000))
                path.curve(to: .init(x: 4.0000000, y: 8.0000000), controlPoint1: .init(x: 4.3357864, y: 8.7500000), controlPoint2: .init(x: 4.0000000, y: 8.4142136))
                layers.append(path)
            }
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 1.7880000, y: 4.2960000))
                path.curve(to: .init(x: 2.5900000, y: 2.5900000), controlPoint1: .init(x: 1.9840000, y: 3.4160000), controlPoint2: .init(x: 2.2660000, y: 2.9150000))
                path.curve(to: .init(x: 4.2960000, y: 1.7880000), controlPoint1: .init(x: 2.9140000, y: 2.2650000), controlPoint2: .init(x: 3.4160000, y: 1.9840000))
                path.curve(to: .init(x: 8.0000000, y: 1.5000000), controlPoint1: .init(x: 5.1940000, y: 1.5880000), controlPoint2: .init(x: 6.3870000, y: 1.5000000))
                path.curve(to: .init(x: 11.7040000, y: 1.7880000), controlPoint1: .init(x: 9.6130000, y: 1.5000000), controlPoint2: .init(x: 10.8060000, y: 1.5880000))
                path.curve(to: .init(x: 13.4100000, y: 2.5900000), controlPoint1: .init(x: 12.5840000, y: 1.9840000), controlPoint2: .init(x: 13.0850000, y: 2.2660000))
                path.curve(to: .init(x: 14.2120000, y: 4.2960000), controlPoint1: .init(x: 13.7350000, y: 2.9140000), controlPoint2: .init(x: 14.0170000, y: 3.4160000))
                path.curve(to: .init(x: 14.5000000, y: 8.0000000), controlPoint1: .init(x: 14.4120000, y: 5.1940000), controlPoint2: .init(x: 14.5000000, y: 6.3870000))
                path.curve(to: .init(x: 14.2120000, y: 11.7040000), controlPoint1: .init(x: 14.5000000, y: 9.6130000), controlPoint2: .init(x: 14.4120000, y: 10.8060000))
                path.curve(to: .init(x: 13.4100000, y: 13.4100000), controlPoint1: .init(x: 14.0170000, y: 12.5840000), controlPoint2: .init(x: 13.7340000, y: 13.0850000))
                path.curve(to: .init(x: 11.7040000, y: 14.2120000), controlPoint1: .init(x: 13.0860000, y: 13.7350000), controlPoint2: .init(x: 12.5840000, y: 14.0170000))
                path.curve(to: .init(x: 8.0000000, y: 14.5000000), controlPoint1: .init(x: 10.8060000, y: 14.4120000), controlPoint2: .init(x: 9.6130000, y: 14.5000000))
                path.curve(to: .init(x: 4.2960000, y: 14.2120000), controlPoint1: .init(x: 6.3870000, y: 14.5000000), controlPoint2: .init(x: 5.1940000, y: 14.4120000))
                path.curve(to: .init(x: 2.5900000, y: 13.4100000), controlPoint1: .init(x: 3.4160000, y: 14.0170000), controlPoint2: .init(x: 2.9150000, y: 13.7340000))
                path.curve(to: .init(x: 1.7880000, y: 11.7040000), controlPoint1: .init(x: 2.2650000, y: 13.0860000), controlPoint2: .init(x: 1.9840000, y: 12.5840000))
                path.curve(to: .init(x: 1.5000000, y: 8.0000000), controlPoint1: .init(x: 1.5880000, y: 10.8060000), controlPoint2: .init(x: 1.5000000, y: 9.6130000))
                path.curve(to: .init(x: 1.7880000, y: 4.2960000), controlPoint1: .init(x: 1.5000000, y: 6.3870000), controlPoint2: .init(x: 1.5880000, y: 5.1940000))
                path.move(to: .init(x: 8.0000000, y: 0.0000000))
                path.curve(to: .init(x: 0.0000000, y: 8.0000000), controlPoint1: .init(x: 1.4120000, y: 0.0000000), controlPoint2: .init(x: 0.0000000, y: 1.4120000))
                path.curve(to: .init(x: 8.0000000, y: 16.0000000), controlPoint1: .init(x: 0.0000000, y: 14.5880000), controlPoint2: .init(x: 1.4120000, y: 16.0000000))
                path.curve(to: .init(x: 16.0000000, y: 8.0000000), controlPoint1: .init(x: 14.5880000, y: 16.0000000), controlPoint2: .init(x: 16.0000000, y: 14.5880000))
                path.curve(to: .init(x: 8.0000000, y: 0.0000000), controlPoint1: .init(x: 16.0000000, y: 1.4120000), controlPoint2: .init(x: 14.5880000, y: 0.0000000))
                layers.append(path)
            }
            result[.deleted] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 1.7880000, y: 4.2960000))
                path.curve(to: .init(x: 2.5900000, y: 2.5900000), controlPoint1: .init(x: 1.9840000, y: 3.4160000), controlPoint2: .init(x: 2.2660000, y: 2.9150000))
                path.curve(to: .init(x: 4.2960000, y: 1.7880000), controlPoint1: .init(x: 2.9140000, y: 2.2650000), controlPoint2: .init(x: 3.4160000, y: 1.9840000))
                path.curve(to: .init(x: 8.0000000, y: 1.5000000), controlPoint1: .init(x: 5.1940000, y: 1.5880000), controlPoint2: .init(x: 6.3870000, y: 1.5000000))
                path.curve(to: .init(x: 11.7040000, y: 1.7880000), controlPoint1: .init(x: 9.6130000, y: 1.5000000), controlPoint2: .init(x: 10.8060000, y: 1.5880000))
                path.curve(to: .init(x: 13.4100000, y: 2.5900000), controlPoint1: .init(x: 12.5840000, y: 1.9840000), controlPoint2: .init(x: 13.0850000, y: 2.2660000))
                path.curve(to: .init(x: 14.2120000, y: 4.2960000), controlPoint1: .init(x: 13.7350000, y: 2.9140000), controlPoint2: .init(x: 14.0170000, y: 3.4160000))
                path.curve(to: .init(x: 14.5000000, y: 8.0000000), controlPoint1: .init(x: 14.4120000, y: 5.1940000), controlPoint2: .init(x: 14.5000000, y: 6.3870000))
                path.curve(to: .init(x: 14.2120000, y: 11.7040000), controlPoint1: .init(x: 14.5000000, y: 9.6130000), controlPoint2: .init(x: 14.4120000, y: 10.8060000))
                path.curve(to: .init(x: 13.4100000, y: 13.4100000), controlPoint1: .init(x: 14.0170000, y: 12.5840000), controlPoint2: .init(x: 13.7340000, y: 13.0850000))
                path.curve(to: .init(x: 11.7040000, y: 14.2120000), controlPoint1: .init(x: 13.0860000, y: 13.7350000), controlPoint2: .init(x: 12.5840000, y: 14.0170000))
                path.curve(to: .init(x: 8.0000000, y: 14.5000000), controlPoint1: .init(x: 10.8060000, y: 14.4120000), controlPoint2: .init(x: 9.6130000, y: 14.5000000))
                path.curve(to: .init(x: 4.2960000, y: 14.2120000), controlPoint1: .init(x: 6.3870000, y: 14.5000000), controlPoint2: .init(x: 5.1940000, y: 14.4120000))
                path.curve(to: .init(x: 2.5900000, y: 13.4100000), controlPoint1: .init(x: 3.4160000, y: 14.0170000), controlPoint2: .init(x: 2.9150000, y: 13.7340000))
                path.curve(to: .init(x: 1.7880000, y: 11.7040000), controlPoint1: .init(x: 2.2650000, y: 13.0860000), controlPoint2: .init(x: 1.9840000, y: 12.5840000))
                path.curve(to: .init(x: 1.5000000, y: 8.0000000), controlPoint1: .init(x: 1.5880000, y: 10.8060000), controlPoint2: .init(x: 1.5000000, y: 9.6130000))
                path.curve(to: .init(x: 1.7880000, y: 4.2960000), controlPoint1: .init(x: 1.5000000, y: 6.3870000), controlPoint2: .init(x: 1.5880000, y: 5.1940000))
                path.move(to: .init(x: 8.0000000, y: 0.0000000))
                path.curve(to: .init(x: 0.0000000, y: 8.0000000), controlPoint1: .init(x: 1.4120000, y: 0.0000000), controlPoint2: .init(x: 0.0000000, y: 1.4120000))
                path.curve(to: .init(x: 8.0000000, y: 16.0000000), controlPoint1: .init(x: 0.0000000, y: 14.5880000), controlPoint2: .init(x: 1.4120000, y: 16.0000000))
                path.curve(to: .init(x: 16.0000000, y: 8.0000000), controlPoint1: .init(x: 14.5880000, y: 16.0000000), controlPoint2: .init(x: 16.0000000, y: 14.5880000))
                path.curve(to: .init(x: 8.0000000, y: 0.0000000), controlPoint1: .init(x: 16.0000000, y: 1.4120000), controlPoint2: .init(x: 14.5880000, y: 0.0000000))
                layers.append(path)
            }
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 8.4950000, y: 4.6950000))
                path.curve(to: .init(x: 8.2503150, y: 5.2146375), controlPoint1: .init(x: 8.3477173, y: 4.8288824), controlPoint2: .init(x: 8.2596932, y: 5.0158191))
                path.curve(to: .init(x: 8.4450000, y: 5.7550000), controlPoint1: .init(x: 8.2409368, y: 5.4134559), controlPoint2: .init(x: 8.3109736, y: 5.6078483))
                path.line(to: .init(x: 10.4860000, y: 8.0000000))
                path.line(to: .init(x: 8.4450000, y: 10.2460000))
                path.curve(to: .init(x: 8.5101972, y: 11.2893661), controlPoint1: .init(x: 8.1808382, y: 10.5541383), controlPoint2: .init(x: 8.2097306, y: 11.0165100))
                path.curve(to: .init(x: 9.5550000, y: 11.2540000), controlPoint1: .init(x: 8.8106638, y: 11.5622223), controlPoint2: .init(x: 9.2736721, y: 11.5465497))
                path.line(to: .init(x: 12.0550000, y: 8.5040000))
                path.curve(to: .init(x: 12.0550000, y: 7.4960000), controlPoint1: .init(x: 12.3144489, y: 8.2180846), controlPoint2: .init(x: 12.3144489, y: 7.7819154))
                path.line(to: .init(x: 9.5550000, y: 4.7460000))
                path.curve(to: .init(x: 9.0355704, y: 4.5008011), controlPoint1: .init(x: 9.4212550, y: 4.5985767), controlPoint2: .init(x: 9.2343915, y: 4.5103670))
                path.curve(to: .init(x: 8.4950000, y: 4.6950000), controlPoint1: .init(x: 8.8367493, y: 4.4912352), controlPoint2: .init(x: 8.6422804, y: 4.5610977))
                path.move(to: .init(x: 4.4950000, y: 4.6950000))
                path.curve(to: .init(x: 4.2503150, y: 5.2146375), controlPoint1: .init(x: 4.3477173, y: 4.8288824), controlPoint2: .init(x: 4.2596932, y: 5.0158191))
                path.curve(to: .init(x: 4.4450000, y: 5.7550000), controlPoint1: .init(x: 4.2409368, y: 5.4134559), controlPoint2: .init(x: 4.3109736, y: 5.6078483))
                path.line(to: .init(x: 6.4890000, y: 8.0030000))
                path.line(to: .init(x: 4.6930000, y: 9.9980000))
                path.curve(to: .init(x: 4.7584115, y: 11.0454478), controlPoint1: .init(x: 4.4262049, y: 10.3067990), controlPoint2: .init(x: 4.4552710, y: 10.7722404))
                path.curve(to: .init(x: 5.8070000, y: 11.0020000), controlPoint1: .init(x: 5.0615520, y: 11.3186553), controlPoint2: .init(x: 5.5275003, y: 11.2993489))
                path.line(to: .init(x: 8.0570000, y: 8.5020000))
                path.curve(to: .init(x: 8.0550000, y: 7.4950000), controlPoint1: .init(x: 8.3152776, y: 8.2157205), controlPoint2: .init(x: 8.3144127, y: 7.7802513))
                path.line(to: .init(x: 5.5550000, y: 4.7450000))
                path.curve(to: .init(x: 5.0353625, y: 4.5003150), controlPoint1: .init(x: 5.4211176, y: 4.5977173), controlPoint2: .init(x: 5.2341809, y: 4.5096932))
                path.curve(to: .init(x: 4.4950000, y: 4.6950000), controlPoint1: .init(x: 4.8365441, y: 4.4909368), controlPoint2: .init(x: 4.6421517, y: 4.5609736))
                layers.append(path)
            }
            result[.moved] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 3.4700000, y: 5.4700000))
                path.curve(to: .init(x: 4.5300000, y: 5.4700000), controlPoint1: .init(x: 3.7628175, y: 5.1775466), controlPoint2: .init(x: 4.2371825, y: 5.1775466))
                path.line(to: .init(x: 8.0000000, y: 8.9400000))
                path.line(to: .init(x: 11.4700000, y: 5.4700000))
                path.curve(to: .init(x: 12.2042889, y: 5.2546145), controlPoint1: .init(x: 11.6569706, y: 5.2693468), controlPoint2: .init(x: 11.9385555, y: 5.1867508))
                path.curve(to: .init(x: 12.7453855, y: 5.7957111), controlPoint1: .init(x: 12.4700223, y: 5.3224781), controlPoint2: .init(x: 12.6775219, y: 5.5299777))
                path.curve(to: .init(x: 12.5300000, y: 6.5300000), controlPoint1: .init(x: 12.8132492, y: 6.0614445), controlPoint2: .init(x: 12.7306532, y: 6.3430294))
                path.line(to: .init(x: 8.5300000, y: 10.5300000))
                path.curve(to: .init(x: 7.4700000, y: 10.5300000), controlPoint1: .init(x: 8.2371825, y: 10.8224534), controlPoint2: .init(x: 7.7628175, y: 10.8224534))
                path.line(to: .init(x: 3.4700000, y: 6.5300000))
                path.curve(to: .init(x: 3.4700000, y: 5.4700000), controlPoint1: .init(x: 3.1775466, y: 6.2371825), controlPoint2: .init(x: 3.1775466, y: 5.7628175))
                layers.append(path)
            }
            result[.expand] = layers
        }
        do {
            var layers: [NSBezierPath] = []
            do {
                let path = NSBezierPath()
                path.move(to: .init(x: 11.4700000, y: 9.4700000))
                path.curve(to: .init(x: 12.2042889, y: 9.2546145), controlPoint1: .init(x: 11.6569706, y: 9.2693468), controlPoint2: .init(x: 11.9385555, y: 9.1867508))
                path.curve(to: .init(x: 12.7453855, y: 9.7957111), controlPoint1: .init(x: 12.4700223, y: 9.3224781), controlPoint2: .init(x: 12.6775219, y: 9.5299777))
                path.curve(to: .init(x: 12.5300000, y: 10.5300000), controlPoint1: .init(x: 12.8132492, y: 10.0614445), controlPoint2: .init(x: 12.7306532, y: 10.3430294))
                path.line(to: .init(x: 8.5300000, y: 14.5300000))
                path.curve(to: .init(x: 7.4700000, y: 14.5300000), controlPoint1: .init(x: 8.2371825, y: 14.8224534), controlPoint2: .init(x: 7.7628175, y: 14.8224534))
                path.line(to: .init(x: 3.4700000, y: 10.5300000))
                path.curve(to: .init(x: 3.2546145, y: 9.7957111), controlPoint1: .init(x: 3.2693468, y: 10.3430294), controlPoint2: .init(x: 3.1867508, y: 10.0614445))
                path.curve(to: .init(x: 3.7957111, y: 9.2546145), controlPoint1: .init(x: 3.3224781, y: 9.5299777), controlPoint2: .init(x: 3.5299777, y: 9.3224781))
                path.curve(to: .init(x: 4.5300000, y: 9.4700000), controlPoint1: .init(x: 4.0614445, y: 9.1867508), controlPoint2: .init(x: 4.3430294, y: 9.2693468))
                path.line(to: .init(x: 8.0000000, y: 12.9400000))
                path.close()
                path.move(to: .init(x: 7.5260000, y: 1.4180000))
                path.curve(to: .init(x: 8.5300000, y: 1.4700000), controlPoint1: .init(x: 7.8244711, y: 1.1752661), controlPoint2: .init(x: 8.2582023, y: 1.1977302))
                path.line(to: .init(x: 12.5300000, y: 5.4700000))
                path.curve(to: .init(x: 12.7453855, y: 6.2042889), controlPoint1: .init(x: 12.7306532, y: 5.6569706), controlPoint2: .init(x: 12.8132492, y: 5.9385555))
                path.curve(to: .init(x: 12.2042889, y: 6.7453855), controlPoint1: .init(x: 12.6775219, y: 6.4700223), controlPoint2: .init(x: 12.4700223, y: 6.6775219))
                path.curve(to: .init(x: 11.4700000, y: 6.5300000), controlPoint1: .init(x: 11.9385555, y: 6.8132492), controlPoint2: .init(x: 11.6569706, y: 6.7306532))
                path.line(to: .init(x: 8.0000000, y: 3.0600000))
                path.line(to: .init(x: 4.5300000, y: 6.5300000))
                path.curve(to: .init(x: 3.7957111, y: 6.7453855), controlPoint1: .init(x: 4.3430294, y: 6.7306532), controlPoint2: .init(x: 4.0614445, y: 6.8132492))
                path.curve(to: .init(x: 3.2546145, y: 6.2042889), controlPoint1: .init(x: 3.5299777, y: 6.6775219), controlPoint2: .init(x: 3.3224781, y: 6.4700223))
                path.curve(to: .init(x: 3.4700000, y: 5.4700000), controlPoint1: .init(x: 3.1867508, y: 5.9385555), controlPoint2: .init(x: 3.2693468, y: 5.6569706))
                path.line(to: .init(x: 7.4700000, y: 1.4700000))
                path.close()
                layers.append(path)
            }
            result[.expandAll] = layers
        }
        return result
    }()
}

#endif
