#!/usr/bin/env python3
"""Bake upstream SVG symbols into native paths; no SVG parser runs in the app.

Usage: python3 Scripts/generate-native-symbols.py /path/to/diffs/src/sprite.ts [--check]
SVG elliptical arcs are converted to cubic segments of at most 90 degrees.
"""
import argparse
import math
import re
from pathlib import Path
from xml.etree import ElementTree as ET

SYMBOLS = {
    'plus': 'plus', 'fileCode': 'file-code', 'modified': 'symbol-modified',
    'added': 'symbol-added', 'deleted': 'symbol-deleted',
    'moved': 'symbol-moved', 'expand': 'expand', 'expandAll': 'expand-all',
}

def point(p):
    return f'.init(x: {p[0]:.7f}, y: {p[1]:.7f})'

def arc(start, values, end):
    rx, ry, rotation, large, sweep = values[:5]
    rx, ry = abs(rx), abs(ry)
    if start == end:
        return []
    if rx == 0 or ry == 0:
        return [('L', end)]
    phi = math.radians(rotation % 360)
    co, si = math.cos(phi), math.sin(phi)
    dx, dy = (start[0] - end[0]) / 2, (start[1] - end[1]) / 2
    x, y = co * dx + si * dy, -si * dx + co * dy
    scale = x*x / (rx*rx) + y*y / (ry*ry)
    if scale > 1:
        rx *= math.sqrt(scale); ry *= math.sqrt(scale)
    numerator = max(0, rx*rx*ry*ry - rx*rx*y*y - ry*ry*x*x)
    denominator = rx*rx*y*y + ry*ry*x*x
    factor = (-1 if bool(large) == bool(sweep) else 1) * math.sqrt(numerator / denominator)
    cx, cy = factor * rx * y / ry, -factor * ry * x / rx
    center = (co*cx - si*cy + (start[0]+end[0])/2, si*cx + co*cy + (start[1]+end[1])/2)
    u = ((x-cx)/rx, (y-cy)/ry); v = ((-x-cx)/rx, (-y-cy)/ry)
    angle = math.atan2(u[1], u[0])
    delta = math.atan2(u[0]*v[1]-u[1]*v[0], u[0]*v[0]+u[1]*v[1])
    if not sweep and delta > 0: delta -= 2*math.pi
    if sweep and delta < 0: delta += 2*math.pi
    count = max(1, math.ceil(abs(delta)/(math.pi/2)))
    step = delta/count
    def at(t):
        return (center[0]+co*rx*math.cos(t)-si*ry*math.sin(t), center[1]+si*rx*math.cos(t)+co*ry*math.sin(t))
    def tangent(t):
        return (-co*rx*math.sin(t)-si*ry*math.cos(t), -si*rx*math.sin(t)+co*ry*math.cos(t))
    output = []
    for i in range(count):
        a, b = angle+i*step, angle+(i+1)*step
        p, q, dp, dq = at(a), at(b), tangent(a), tangent(b)
        k = 4/3*math.tan(step/4)
        output.append(('C', (p[0]+k*dp[0], p[1]+k*dp[1]), (q[0]-k*dq[0], q[1]-k*dq[1]), end if i == count-1 else q))
    return output

def commands(data):
    tokens = re.findall(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?', data)
    output = []; i = 0; command = ''; previous = ''
    current = (0., 0.); start = current; control = current
    sizes = dict(M=2, L=2, H=1, V=1, C=6, S=4, Q=4, T=2, A=7)
    while i < len(tokens):
        if tokens[i].isalpha(): command = tokens[i]; i += 1
        kind = command.upper()
        if kind == 'Z':
            output.append(('Z',)); current = start; previous = kind; command = ''; continue
        if kind not in sizes: raise ValueError(f'Unsupported command: {command}')
        size = sizes[kind]; values = list(map(float, tokens[i:i+size])); i += size
        def pos(x, y):
            return (x+current[0], y+current[1]) if command.islower() else (x, y)
        if kind in ('M', 'L', 'T'):
            end = pos(*values)
            if kind == 'M':
                output.append(('M', end)); start = end; command = 'l' if command.islower() else 'L'
            elif kind == 'L': output.append(('L', end))
            else:
                reflected = (2*current[0]-control[0], 2*current[1]-control[1]) if previous in ('Q', 'T') else current
                output.append(('Q', reflected, end)); control = reflected
        elif kind in ('H', 'V'):
            end = (values[0] + (current[0] if command.islower() else 0), current[1]) if kind == 'H' else (current[0], values[0] + (current[1] if command.islower() else 0))
            output.append(('L', end))
        elif kind == 'C':
            c1, c2, end = [pos(*values[j:j+2]) for j in (0, 2, 4)]
            output.append(('C', c1, c2, end)); control = c2
        elif kind == 'S':
            c1 = (2*current[0]-control[0], 2*current[1]-control[1]) if previous in ('C', 'S') else current
            c2, end = pos(*values[:2]), pos(*values[2:])
            output.append(('C', c1, c2, end)); control = c2
        elif kind == 'Q':
            control, end = pos(*values[:2]), pos(*values[2:]); output.append(('Q', control, end))
        else:
            end = pos(*values[5:]); output.extend(arc(current, values, end))
        current = end; previous = kind
    return output

def generate(source):
    svg = source[source.index('<svg'):source.index('</svg>')+6]
    root = ET.fromstring("<svg>" + svg[svg.index(">")+1:])
    symbols = {node.attrib.get('id'): node for node in root.iter() if node.tag.endswith('symbol')}
    lines = ['// Generated by Scripts/diffs/generate-native-symbols.py from @pierre/diffs src/sprite.ts.',
             '// Upstream vector artwork is Apache-2.0 licensed; see LICENSE.',
             '// Arc conversion is performed at generation time, never while rendering.',
             'import AppKit', '', '@MainActor enum DiffSymbol: CaseIterable {',
             '    case ' + ', '.join(SYMBOLS), '',
             '    func draw(in rect: NSRect, color: NSColor, flipY: Bool = false) {',
             '        NSGraphicsContext.saveGraphicsState()',
             '        defer { NSGraphicsContext.restoreGraphicsState() }',
             '        let transform = NSAffineTransform()',
             '        transform.translateX(by: rect.minX, yBy: flipY ? rect.maxY : rect.minY)',
             '        transform.scaleX(by: rect.width / 16, yBy: (flipY ? -1 : 1) * rect.height / 16)',
             '        transform.concat(); color.setFill()',
             '        for path in Self.paths[self] ?? [] { path.fill() }',
             '    }', '', '    private static let paths: [DiffSymbol: [NSBezierPath]] = {',
             '        var result: [DiffSymbol: [NSBezierPath]] = [:]']
    for name, ident in SYMBOLS.items():
        symbol = symbols['diffs-icon-'+ident]
        assert symbol.attrib['viewBox'] == '0 0 16 16'
        lines.append('        do {'); lines.append('            var layers: [NSBezierPath] = []')
        for node in symbol:
            assert node.tag.endswith('path') and set(node.attrib) <= {'d', 'fill-rule', 'clip-rule'}
            lines.append('            do {'); lines.append('                let path = NSBezierPath()')
            if node.attrib.get('fill-rule') == 'evenodd': lines.append('                path.windingRule = .evenOdd')
            current = (0., 0.)
            for command in commands(node.attrib['d']):
                kind, *points = command
                if kind == 'M': code = f'path.move(to: {point(points[0])})'
                elif kind == 'L': code = f'path.line(to: {point(points[0])})'
                elif kind == 'C': code = f'path.curve(to: {point(points[2])}, controlPoint1: {point(points[0])}, controlPoint2: {point(points[1])})'
                elif kind == 'Q':
                    c, end = points
                    c1 = tuple(current[j]+2/3*(c[j]-current[j]) for j in (0, 1)); c2 = tuple(end[j]+2/3*(c[j]-end[j]) for j in (0, 1))
                    code = f'path.curve(to: {point(end)}, controlPoint1: {point(c1)}, controlPoint2: {point(c2)})'
                else: code = 'path.close()'
                if points: current = points[-1]
                lines.append('                '+code)
            lines.extend(['                layers.append(path)', '            }'])
        lines.extend([f'            result[.{name}] = layers', '        }'])
    lines.extend(['        return result', '    }()', '}', ''])
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('sprite', type=Path); parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    # AppKit drawing: the whole file is macOS-only, like the rest of ShikiDiffs' views.
    result = '#if os(macOS)\n' + generate(args.sprite.read_text()) + '\n#endif\n'
    destination = Path(__file__).resolve().parents[2] / 'Sources/ShikiDiffs/DiffSymbol.swift'
    if args.check:
        if destination.read_text() != result: raise SystemExit('Native symbols are out of date')
        print('Native symbols match upstream sprite')
    else:
        destination.write_text(result)
        print(f'Generated {len(SYMBOLS)} native symbols')
