// Isolate the standalone regex engine from other libraries in the host app.
#define __dbuf_put_u16 sdq___dbuf_put_u16
#define __dbuf_put_u32 sdq___dbuf_put_u32
#define __dbuf_put_u64 sdq___dbuf_put_u64
#define __dbuf_putc sdq___dbuf_putc
#define cr_copy sdq_cr_copy
#define cr_free sdq_cr_free
#define cr_init sdq_cr_init
#define cr_invert sdq_cr_invert
#define cr_op sdq_cr_op
#define cr_op1 sdq_cr_op1
#define cr_realloc sdq_cr_realloc
#define cr_regexp_canonicalize sdq_cr_regexp_canonicalize
#define dbuf_claim sdq_dbuf_claim
#define dbuf_free sdq_dbuf_free
#define dbuf_init sdq_dbuf_init
#define dbuf_init2 sdq_dbuf_init2
#define dbuf_printf sdq_dbuf_printf
#define dbuf_put sdq_dbuf_put
#define dbuf_put_self sdq_dbuf_put_self
#define dbuf_putstr sdq_dbuf_putstr
#define has_suffix sdq_has_suffix
#define lre_canonicalize sdq_lre_canonicalize
#define lre_case_conv sdq_lre_case_conv
#define lre_check_stack_overflow sdq_lre_check_stack_overflow
#define lre_check_timeout sdq_lre_check_timeout
#define lre_compile sdq_lre_compile
#define lre_ctype_bits sdq_lre_ctype_bits
#define lre_exec sdq_lre_exec
#define lre_get_alloc_count sdq_lre_get_alloc_count
#define lre_get_capture_count sdq_lre_get_capture_count
#define lre_get_flags sdq_lre_get_flags
#define lre_get_groupnames sdq_lre_get_groupnames
#define lre_is_case_ignorable sdq_lre_is_case_ignorable
#define lre_is_cased sdq_lre_is_cased
#define lre_is_id_continue sdq_lre_is_id_continue
#define lre_is_id_start sdq_lre_is_id_start
#define lre_is_space_non_ascii sdq_lre_is_space_non_ascii
#define lre_parse_escape sdq_lre_parse_escape
#define lre_realloc sdq_lre_realloc
#define pstrcat sdq_pstrcat
#define pstrcpy sdq_pstrcpy
#define rqsort sdq_rqsort
#define strstart sdq_strstart
#define unicode_from_utf8 sdq_unicode_from_utf8
#define unicode_general_category sdq_unicode_general_category
#define unicode_normalize sdq_unicode_normalize
#define unicode_prop sdq_unicode_prop
#define unicode_script sdq_unicode_script
#define unicode_sequence_prop sdq_unicode_sequence_prop
#define unicode_to_utf8 sdq_unicode_to_utf8
